environment:
  access_token:
    secure: qNMRA5boyCslJ9JgiqjpLdHd0NvhQVWcjJx3ZMrcgrDz6DNFJnDsV7w9IZuhqwYZ

build_script:
 - git config --global credential.helper store
 - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
 - git config --global user.email "appveyor@notarealem.ail"
 - git config --global user.name "Appveyor Automated Build"
 - cmd: For /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c-%%a-%%b)
 - cmd: For /f "tokens=1-2 delims=/:" %%a in ('time /t') do (set mytime=%%a:%%b)
 #
 - git checkout master
 - set appvhome=%cd%
 - cd C:\
 - git clone https://github.com/googlei18n/noto-emoji
 - cd noto-emoji
 - "%appvhome%\\internalcopy C:\\noto-emoji\\png %appvhome%\\png /E /IS /NS /NC /NDL /NFL /NP"
 - "%appvhome%\\internalcopy C:\\noto-emoji\\svg %appvhome%\\svg /E /IS /NS /NC /NDL /NFL /NP"
 - git checkout v2017-05-18-cook-color-fix
 - "%appvhome%\\internalcopy C:\\noto-emoji\\png %appvhome%\\png /E /IS /NS /NC /NDL /NFL /NP"
 - "%appvhome%\\internalcopy C:\\noto-emoji\\svg %appvhome%\\svg /E /IS /NS /NC /NDL /NFL /NP"
 - cd %appvhome%
 - git add .
 - git commit --allow-empty -m "Automated Appveyor build at %mydate%, %mytime% [skip ci]"
 - git push origin master
 #
 
